### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by dimitarnestorov** [dimitarnestorov/bedtime#7]

**Comment by KevDoy** [comment]
I'll work on this.

**Comment by KevDoy** [comment]
![image](https://user-images.githubusercontent.com/11251011/67450594-bc252900-f5d2-11e9-9f2e-6115855bc25b.png)


Here's a proof. Thoughts? Comments? Suggestions?

**Comment by dimitarnestorov** [comment]
I like it! My only suggestion is a subtle shadow around the logo so it stands out on white backgrounds.

**Comment by KevDoy** [comment]
Done!
https://github.com/dimitarnestorov/bedtime/pull/12

**Comment by dimitarnestorov** [comment]
Closed via #12
